spout: uprspoutstream

couchbase:
    ip: 127.0.0.1
    port: 8091
    mc_port: 11210 
    vbuckets: 64
    username: Administrator
    password: password

ui:
  enabled: False
  ip: 127.0.0.1
  port: 3000
